#!/usr/bin/perl
# header.pl (p356-357)
# (use 'email.txt' as input to this program)
# ('email.txt' generated by Chapter03/formate.pl)
use warnings;
use strict;

my (@head, @body);

while (<>) {
    if (1 .. /^$/) {
        push @head, $_;
    } else {
        push @body, $_;
        last;   # found start of body, quit loop
    }
}

push @body, <>;
print "Head: \n", @head;
print "Body: \n", @body;
